#!/usr/bin/perl
#takes two textfiles as input: this month and last one.
use HTTP::Date;

$file = shift || die "No file specified";

$inp;
$msgs=0;
$fsa=1;
open(I, "<$file");

while ($_ = <I>) {
    if ($fsa && $_ =~ /^From /) {
        $msgs++;
    }

    $inp[$msgs] .= $_;
    chomp;

    if (!length($_)) {
        $fsa=1;
    }
    else{
        $fsa=0;
    }
}
close I;


$prev = shift || die "No file specified";

open(I, "<$prev");
while ($_ = <I>) {
    if ($fsa && $_ =~ /^From /) {
        $msgs++;
    }

    $inp[$msgs] .= $_;
    chomp;

    if (!length($_)) {
        $fsa=1;
    }
    else{
        $fsa=0;
    }
}
close I;

                         # Only use the last 14 days and split them up in two weeks

$msgs=0;
$epoc = time();
$epoc07 = $epoc - 07 * 24 * 60 * 60;
$epoc14 = $epoc - 14 * 24 * 60 * 60;
foreach my $msg (@inp) {
    if ($msg =~ /^From\s+.*at.*\.(.*)$/m) {
        #print "$1\n";
    } else {
        next;
    }
    if ($1 =~ /  (.*)$/m) {
        $dt = str2time($1);
        if ($dt > $epoc07) {
            $msgs++;
            $file[$msgs] = $msg;
        } elsif ($dt > $epoc14) {
            $msgs++;
            $prev[$msgs] = $msg;
        }
    }
}

                         # Find the number of posts


$posts = scalar(@file);


                      # Find the size of the list in K


$size = int(length(join '', @file) / 1024);


                        # Find how many people posted


foreach (@file) {
    /^From:\s+(.*)\s+(\(.*)$/m;
    $mails{$1}=$2;
}

foreach (@file) {
    /^From:\s+(.*)\s+\(.*$/m;
    $whomail=$1." ".$mails{$1};
    if(! defined ($posters{$whomail})) {
        $numposters++;
    }
    $posters{$whomail} += length;
    $posterposts{$whomail} ++;
}

foreach (@prev) {
    /^From:\s+(.*)$/m;
    $prevposters{$1} += length;
}


                # Find how many people posted more than once


$ot = 0;
foreach (keys %posterposts) {
    ($posterposts{$_} > 1) && ($ot++);
}


                    # Find how many posted last week too


$lw = 0;
foreach (keys %prevposters) {
    if($posters{$_}) {
        $lw++;
    }
}


                   # Find the biggest posters of the week.


sub bysizes {
    if($posterposts{$b} == $posterposts{$a}) {
        return $posters{$b} <=> $posters{$a};
    }

    return $posterposts{$b} <=> $posterposts{$a};
}

$onlyeleven=0;
foreach (sort bysizes keys %posterposts) {
    $who = $_;

    #get rid of email addresses
    if(($who =~ /\S\s+(\S*)@\S*/) || ($who =~ /(\S*)@\S*\s+\S/))
    {
        $who =~ s/\S*@\S*//;
    }
    else
    {
        $who =~ s/<?(\S*)@\S*/($1)/;
    }

    $who =~ s/</&lt;/g;
    $who =~ s/>/&gt;/g;
    $who =~ s/"/&quot;/g;
    $who =~ s/\s*$//;

    $who || next;
    $onlyeleven++;
    if ($onlyeleven > 11) {last;}
    push @whos, sprintf "<person posts=\"%d\" size=\"%d\" who=\"%s\" />\n", $posterposts{$_}, $posters{$_}/1024, $who;
}

print "<stats posts=\"$posts\" size=\"$size\" contrib=\"$numposters\" multiples=\"$ot\" lastweek=\"$lw\">\n\n";

print @whos;

print "\n</stats>\n";

